# Using Transformers and a pretrained language model capable of generating text (e.g., GPT)

In [1]:
import tensorflow as tf

In [2]:
from transformers import TFOpenAIGPTLMHeadModel

model = TFOpenAIGPTLMHeadModel.from_pretrained("openai-gpt")

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFOpenAIGPTLMHeadModel: ['h.2.attn.bias', 'h.8.attn.bias', 'h.7.attn.bias', 'h.0.attn.bias', 'h.11.attn.bias', 'h.9.attn.bias', 'h.6.attn.bias', 'h.4.attn.bias', 'h.10.attn.bias', 'h.5.attn.bias', 'h.3.attn.bias', 'h.1.attn.bias']
- This IS expected if you are initializing TFOpenAIGPTLMHeadModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFOpenAIGPTLMHeadModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFOpenAIGPTLMHeadModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFOpenAIGPTLMHeadModel for predicti

In [3]:
from transformers import OpenAIGPTTokenizer

tokenizer = OpenAIGPTTokenizer.from_pretrained("openai-gpt")

ftfy or spacy is not installed using BERT BasicTokenizer instead of SpaCy & ftfy.


In [6]:
print(tokenizer("hello everyone"))

prompt_text = "This royal throne of kings, this sceptred isle"
encoded_prompt = tokenizer.encode(prompt_text,
                                  add_special_tokens=False,
                                  return_tensors="tf")
encoded_prompt

{'input_ids': [3570, 1473], 'attention_mask': [1, 1]}


<tf.Tensor: shape=(1, 10), dtype=int32, numpy=
array([[  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187]], dtype=int32)>

In [7]:
num_sequences = 5
length = 40

generated_sequences = model.generate(
    input_ids=encoded_prompt,
    do_sample=True,
    max_length=length + len(encoded_prompt[0]),
    temperature=1.0,
    top_k=0,
    top_p=0.9,
    repetition_penalty=1.0,
    num_return_sequences=num_sequences,
)

generated_sequences

<tf.Tensor: shape=(5, 50), dtype=int32, numpy=
array([[  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   240,   481,  1632,  1807,   498,   618, 22170,   239,
          498,   481,  4031,   240,   664,  1872,  1252,   562, 11665,
          240,   504,   481, 19995,   498,   734,  4646,   240, 38531,
         5466,   240,   488,  6151, 39276,   240,   504,   481, 12191,
          498,   734,  4646,   488,  6151],
       [  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   239,   488,   507,   544,   603,   525,   507,   636,
          580,  1347, 14306,  2510,   522,   481,    11,  1060,   552,
        10707,   240,   912,   481,  3762,   509,  2160,   655,   485,
         3013,   481,  6848,   485,    10,   960,   799,   239,   256,
        40477,   481,  1122,   618,   816],
       [  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   939,   485,   580,  1816,   557,  6826,   535,   637,
           11

In [8]:
for sequence in generated_sequences:
    text = tokenizer.decode(sequence, clean_up_tokenization_spaces=True)
    print(text)
    print("-" * 80)

this royal throne of kings, this sceptred isle, the lost city of king stor. of the ships, no longer used for sailing, on the shores of parri, aeneas, and sherzad, on the seas of parri and sher
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle. and it is said that it would be called dragonwood or the idealethorn, because the bridge was placed there to protect the passage to daligo.'
 the old king looked
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle came to be known as england's soiree for the upcoming great danes of england, and to'the green realms of king canute '. canute's son richard the lionheart was also the king
--------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle. it lies in grave peril. it is an offense that will have to be treated with care and de